version: '3'
services:
  backend:
    image: algocean/backend
    cpu_count: 4
    build:
      context: ./
      dockerfile: Dockerfile
      
    ports:
      - 8501-8506:8501-8506 # for the user streamlit app
      - 8265:8265
      - 8000:8000
      - 8888:8888
      - 8001:8001
      - 7865-7870:7865-7870
      
    volumes:
      - ./ipfspy/ipfspy:/app/ipfspy/ipfspy
      - ./ipfsspec/ipfsspec:/app/ipfsspec/ipfsspec
      - ./ocean.py/ocean_lib:/app/ocean.py/ocean_lib
      - ./algocean:/app/algocean
      - ${OCEAN_ARTIFACTS_FOLDER}:/.ocean/ocean-contracts/artifacts
      - ./artifacts:/app/artifacts
      - ./contracts:/app/contracts
      - ./interfaces:/app/interfaces
      - ./scripts:/app/scripts
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Makefile:/app/Makefile
      - ./.bittensor:/root/.bittensor
      - /tmp/wholetensor:/tmp
      - /home/ubuntu/efs:/efs
    networks:
      backend:
        ipv4_address: 172.15.0.9

    environment:
      OCEAN_ARTIFACTS_FOLDER: /.ocean/ocean-contracts/artifacts"
      ADDRESS_FILE: /.ocean/ocean-contracts/artifacts/address.json
      OCEAN_NETWORK_URL: ${NETWORK_RPC_URL}
      LOCAL_NETWORK_RPC_URL: ${NETWORK_RPC_URL}
      GANACHE_URL: ${GANACHE_URL}
      PRIVATE_KEY: ${PRIVATE_KEY}
    env_file: 
      - .env
    command: bash -c "chmod +x ./scripts/*; conda init bash;./scripts/startup.sh; conda activate algocean; tail -F anything"

    deploy:
      resources:
         reservations:
           devices:
           - driver: nvidia
             count: 'all'
             capabilities: [gpu]


networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.15.0.1/24

