gradio_api:
	python algocean/gradio/api/module.py --api

api:
	python algocean/gradio/api/module.py --api

python:
	python algocean/${arg}/module.py


app:
	streamlit algocean/${arg}/module.py

jupyter:
	jupyter-lab --ip=0.0.0.0 --no-browser --allow-root
